name: Test Supported Distributions

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  smoke-tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          fetch-depth: 0 # Differential ShellCheck requires full git history

      - name: Check scripts in repository are executable
        run: |
          IFS=$'\n';
          for f in $(find . -name '*.sh' -o -name '*.bats'); do if [[ ! -x $f ]]; then echo "$f is not executable" && FAIL=1; fi ;done
          unset IFS;
          # If FAIL is 1 then we fail.
          [[ $FAIL == 1 ]] && exit 1 || echo "Scripts are executable!"

      - name: Differential ShellCheck
        uses: redhat-plumbers-in-action/differential-shellcheck@d965e66ec0b3b2f821f75c8eff9b12442d9a7d1e #v5.5.6
        with:
          severity: warning
          display-engine: sarif-fmt

      - name: Secret Scanning with TruffleHog
        uses: trufflesecurity/trufflehog@bcfcf73aaf4759d4dadc2783177c245a02792318 #v3.97.0
        with:
          extra_args: --results=verified,unknown

      - name: Spell-Checking
        uses: codespell-project/actions-codespell@8f01853be192eb0f849a5c7d721450e7a467c579 #v2.2
        with:
          ignore_words_file: .codespellignore

      - name: Get editorconfig-checker
        uses: editorconfig-checker/action-editorconfig-checker@840e866d93b8e032123c23bac69dece044d4d84c #v2.2.0

      - name: Run editorconfig-checker
        run: editorconfig-checker

  distro-test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    needs: smoke-tests
    strategy:
      fail-fast: false
      matrix:
        distro:
          [
            debian_11,
            debian_12,
            debian_13,
            ubuntu_20,
            ubuntu_22,
            ubuntu_24,
            ubuntu_26,
            centos_9,
            centos_10,
            fedora_40,
            fedora_41,
            fedora_42,
            fedora_43,
            fedora_44,
            alpine_3_21,
            alpine_3_22,
            alpine_3_23,
            alpine_3_24,
          ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1

      - name: Run BATS test suite for ${{ matrix.distro }}
        run: DISTRO=${{ matrix.distro }} bash test/run.sh
